map = {
    'SIL': 'rest.jpg',
    'G': 'E.jpg',
    'OW': 'O.jpg',
    'F': 'FV.jpg',
    'AO': 'O.jpg',
    'R': 'AI.jpg',
    'W': 'WQ.jpg',
    'ER': 'E.jpg',
    'EH': 'E.jpg',
    'D': 'etc.jpg',
    'JH': 'etc.jpg',
    'T': 'L.jpg',
    'EN': 'E.jpg',
    'M': 'MBP.jpg',
    'IY': 'etc.jpg',
    'IH': 'etc.jpg',
    'ZH': 'etc.jpg',
    'Z': 'etc.jpg',
    'S': 'etc.jpg',
    'V': 'U.jpg',
    'N': 'L.jpg'
}